// song_data.js — GENERATED by compile_data.py from genre_chord_bank_v9.xlsx
// Do not hand-edit; edit the workbook and re-run the compiler.
const SONG_DATA = {
  "meta": {
    "source": "genre_chord_bank_v9.xlsx",
    "compiled": "2026-09-02",
    "referenceBpm": 60,
    "note": "Genres carry structure, chords, default BPM and meter only; the band pattern banks were removed on 2026-09-13."
  },
  "reference": [
    {
      "label": "Duration reference (all pattern timings stated at 60 BPM)",
      "value": null
    },
    {
      "label": "Tempo",
      "value": "60 BPM"
    },
    {
      "label": "Quarter Note",
      "value": "1000 ms"
    },
    {
      "label": "4/4 Bar",
      "value": "4000 ms"
    },
    {
      "label": "Whole",
      "value": "4000 ms"
    },
    {
      "label": "Half",
      "value": "2000 ms"
    },
    {
      "label": "Dotted quarter",
      "value": "1500 ms"
    },
    {
      "label": "Quarter",
      "value": "1000 ms"
    },
    {
      "label": "Dotted 8th",
      "value": "750 ms"
    },
    {
      "label": "8th",
      "value": "500 ms"
    },
    {
      "label": "Swing long 8th (2:1)",
      "value": "667 ms"
    },
    {
      "label": "Triplet 8th",
      "value": "333 ms"
    },
    {
      "label": "Swing short 8th",
      "value": "333 ms"
    },
    {
      "label": "16th",
      "value": "250 ms"
    },
    {
      "label": "32nd",
      "value": "125 ms"
    },
    {
      "label": "Sheet notes",
      "value": null
    },
    {
      "label": "Genre_Chord_Bank:",
      "value": "Hyphens are one chord per bar. A pre-chorus of IV-V-vi-V means bar 1 = IV, bar 2 = V, bar 3 = vi, bar 4 = V."
    },
    {
      "label": "Genre_Pattern_Map:",
      "value": "Pattern names match Guitar_Strum_Bank exactly. Bass default names a rhythm pattern from the same bank plus how to voice it (roots, root-fifth, octaves). Default BPM sits inside the pattern's BPM range. Edit any cell — this sheet is meant to be corrected."
    },
    {
      "label": "Piano_Pattern_Bank:",
      "value": "Same timing scheme as Guitar_Strum_Bank (60 BPM reference). Hands column describes LH/RH roles. When piano is the accompaniment instrument, its LH covers the bass role, so the Bass default column applies only when a separate bass instrument is used. Slash values in Ratio/Sustain/Mute alternate per slot, same convention as the guitar sheet."
    },
    {
      "label": "Instruments:",
      "value": "Timbre is separate from pattern. An instrument names which pattern bank it plays from; several instruments can share one bank (acoustic / 12-string / electric all use Guitar_Strum_Bank; bass guitar / 808 / tuba all use Bass_Pattern_Bank). Trumpet and clarinet carry the melody or a countermelody, so they have ranges and timbres but no pattern bank."
    },
    {
      "label": "Bass_Pattern_Bank:",
      "value": "Note choice column says which chord tones the pattern uses. Genre_Pattern_Map's bass column now references these pattern names exactly."
    },
    {
      "label": "Ensemble_Pattern_Bank:",
      "value": "Suits column suggests strings vs horns. Ensemble parts are optional color; '—' in the map means the genre usually omits them."
    },
    {
      "label": "Register_Map:",
      "value": "Defaults for where each role sits relative to the melody. The app applies these automatically when building a song, then lets the user drag any part to a different octave. Hard clamps come from the Instruments sheet ranges — the app warns when a part exceeds its instrument."
    },
    {
      "label": "Custom rows:",
      "value": "Custom entry is two-tier. SIMPLE (default): the user enters just chords, notes, and rhythm — nothing else. The envelope fills in automatically by slot length: slots ≥ 2000 ms → ratio 0.90 · 1000 ms → 0.80 · 500 ms → 0.70 · 250 ms → 0.60 · ≤ 125 ms → 1.00 · swing pairs → 0.75 / 0.50 (values borrowed from the straight presets in the banks). ADVANCED (behind a toggle, labeled 'Fine-tune the feel'): per-slot ratio / sustain / mute, pedal, and accents. A simple-mode custom pattern is stored in the same fields as presets — the auto-filled values are just written for the user."
    },
    {
      "label": "Chord_Vocabulary:",
      "value": "Grammar the progression parser and chord builder support. Plain numerals in Genre_Chord_Bank remain valid and mean root-position triads in key — fully backward compatible. Figured bass (I6, I64, V65) and slash chords (C/E) are two displays of the same data, following the numerals-vs-chord-names toggle. Tier column: Simple chords appear in the quick picker; Advanced appear in the full chord builder."
    }
  ],
  "instruments": [
    {
      "name": "Acoustic guitar",
      "family": "Guitar",
      "patternBank": "Guitar_Strum_Bank",
      "roles": "Accompaniment",
      "rangeLow": "E2",
      "rangeHigh": "E5",
      "polyphony": "Poly (6)",
      "timbre": "Triangle + slight saw, fast attack, natural decay",
      "notes": null
    },
    {
      "name": "12-string guitar",
      "family": "Guitar",
      "patternBank": "Guitar_Strum_Bank",
      "roles": "Accompaniment",
      "rangeLow": "E2",
      "rangeHigh": "E5",
      "polyphony": "Poly (6 doubled)",
      "timbre": "Same as acoustic + octave-up double on lower 4 strings, slight detune shimmer",
      "notes": "Timbre variant — same patterns as acoustic"
    },
    {
      "name": "Electric guitar (clean)",
      "family": "Guitar",
      "patternBank": "Guitar_Strum_Bank",
      "roles": "Accompaniment / riffs",
      "rangeLow": "E2",
      "rangeHigh": "E6",
      "polyphony": "Poly (6)",
      "timbre": "Rounded saw, longer sustain, light chorus",
      "notes": null
    },
    {
      "name": "Electric guitar (drive)",
      "family": "Guitar",
      "patternBank": "Guitar_Strum_Bank",
      "roles": "Accompaniment / power chords",
      "rangeLow": "E2",
      "rangeHigh": "E6",
      "polyphony": "Poly (6)",
      "timbre": "Clipped/overdriven saw, high sustain",
      "notes": "Pairs with palm-mute + power-chord patterns"
    },
    {
      "name": "Bass guitar",
      "family": "Bass",
      "patternBank": "Bass_Pattern_Bank",
      "roles": "Bass",
      "rangeLow": "E1",
      "rangeHigh": "G3",
      "polyphony": "Mono",
      "timbre": "Sine + triangle blend, fast attack, medium decay",
      "notes": null
    },
    {
      "name": "Synth / 808 bass",
      "family": "Bass",
      "patternBank": "Bass_Pattern_Bank",
      "roles": "Bass",
      "rangeLow": "C1",
      "rangeHigh": "C3",
      "polyphony": "Mono",
      "timbre": "Pure sine, slow release, optional pitch glide",
      "notes": "Trap / hip-hop / EDM"
    },
    {
      "name": "Tuba",
      "family": "Bass / brass",
      "patternBank": "Bass_Pattern_Bank",
      "roles": "Bass",
      "rangeLow": "D1",
      "rangeHigh": "F4",
      "polyphony": "Mono",
      "timbre": "Soft triangle, breathy attack, round decay",
      "notes": "Plays bass-bank patterns; two-step = oom-pah"
    },
    {
      "name": "Piano",
      "family": "Keys",
      "patternBank": "Piano_Pattern_Bank",
      "roles": "Accompaniment / everything",
      "rangeLow": "A0",
      "rangeHigh": "C8",
      "polyphony": "Poly (10)",
      "timbre": "Bright triangle stack, percussive attack, long decay, pedal = overlap",
      "notes": null
    },
    {
      "name": "Strings section",
      "family": "Ensemble",
      "patternBank": "Ensemble_Pattern_Bank",
      "roles": "Pads / ostinato / color",
      "rangeLow": "C2",
      "rangeHigh": "C7",
      "polyphony": "Poly",
      "timbre": "Detuned saw stack, slow attack, slow release",
      "notes": null
    },
    {
      "name": "Horn section",
      "family": "Ensemble",
      "patternBank": "Ensemble_Pattern_Bank",
      "roles": "Stabs / punches / pads",
      "rangeLow": "A2",
      "rangeHigh": "F5",
      "polyphony": "Poly (3-4)",
      "timbre": "Bright saw, medium-fast attack, medium release",
      "notes": null
    },
    {
      "name": "Trumpet",
      "family": "Lead wind",
      "patternBank": "(melody — no bank)",
      "roles": "Melody / countermelody",
      "rangeLow": "F#3",
      "rangeHigh": "D6",
      "polyphony": "Mono",
      "timbre": "Bright saw, crisp attack",
      "notes": "Plays the melody or a countermelody line, not patterns"
    },
    {
      "name": "Clarinet",
      "family": "Lead wind",
      "patternBank": "(melody — no bank)",
      "roles": "Melody / countermelody",
      "rangeLow": "D3",
      "rangeHigh": "Bb6",
      "polyphony": "Mono",
      "timbre": "Square wave (odd harmonics), soft attack",
      "notes": "Plays the melody or a countermelody line, not patterns"
    }
  ],
  "registerMap": [
    {
      "role": "Melody (voice / lead)",
      "defaultRegister": "C4–C6",
      "positionVsMelody": "—",
      "voicingRule": "Set by the singer's entered notes; everything else positions around it.",
      "hardClamp": "Instrument range if a lead instrument plays it"
    },
    {
      "role": "Sub vocal (duet partner)",
      "defaultRegister": "C4–C6 (or singer's own range)",
      "positionVsMelody": "Same register as lead, or a 3rd above / below when harmonizing",
      "voicingRule": "Call-and-response: sings in the lead's rests. Unison/harmony: rhythm locks to the lead's syllable chips, pitch offset by the chosen interval.",
      "hardClamp": "Singer's range"
    },
    {
      "role": "Backup vocals",
      "defaultRegister": "G3–G5",
      "positionVsMelody": "Below the lead (3rd / 5th / 6th under)",
      "voicingRule": "Chord tones only; sustained pads ('oohs'), echoes of the lead's last phrase, or short responses. Always quieter than lead and sub; duck under both.",
      "hardClamp": "Singers' range"
    },
    {
      "role": "Countermelody (trumpet / clarinet)",
      "defaultRegister": "G3–G5",
      "positionVsMelody": "Around the melody, answering in its rests",
      "voicingRule": "Never unison with melody; move when melody rests, hold when melody moves.",
      "hardClamp": "Instrument range"
    },
    {
      "role": "Accompaniment chords (guitar / piano RH)",
      "defaultRegister": "C3–C5",
      "positionVsMelody": "Centered ~1 octave below melody center",
      "voicingRule": "Keep the chord's top note at least a 3rd below the current melody note; drop an inversion if the melody dips.",
      "hardClamp": "Instrument range"
    },
    {
      "role": "Piano LH (when piano is sole accompaniment)",
      "defaultRegister": "C2–C4",
      "positionVsMelody": "~2 octaves below melody center",
      "voicingRule": "Covers the bass role; root or root-fifth at the bottom of the voicing.",
      "hardClamp": "A0 lower limit"
    },
    {
      "role": "Bass (bass guitar / 808 / tuba)",
      "defaultRegister": "E1–G3",
      "positionVsMelody": "2–3 octaves below melody center",
      "voicingRule": "Roots stay below C3 whenever accompaniment chords are present; never crosses above the chord voicing.",
      "hardClamp": "Instrument range (E1–G3 bass gtr)"
    },
    {
      "role": "Ensemble pad — low (strings / horns)",
      "defaultRegister": "G2–G4",
      "positionVsMelody": "Below melody, above bass",
      "voicingRule": "Sustains inside the gap between bass and chords; duck volume under melody.",
      "hardClamp": "Instrument range"
    },
    {
      "role": "Ensemble — high (string ostinato / tremolo)",
      "defaultRegister": "C5–C7",
      "positionVsMelody": "Above melody",
      "voicingRule": "Only when melody sits below C5; quieter than melody; drop out if melody rises.",
      "hardClamp": "Instrument range"
    },
    {
      "role": "Horn stabs / punches",
      "defaultRegister": "A2–F5",
      "positionVsMelody": "Between bass and melody",
      "voicingRule": "Hit in the melody's gaps (offbeats, rests); short notes so nothing masks the voice.",
      "hardClamp": "Instrument range"
    }
  ],
  "chordVocabulary": [
    {
      "symbol": "I",
      "name": "Major triad, root position",
      "chordNameInC": "C",
      "tones": "1 3 5",
      "tier": "Simple"
    },
    {
      "symbol": "i",
      "name": "Minor triad",
      "chordNameInC": "Cm",
      "tones": "1 b3 5",
      "tier": "Simple"
    },
    {
      "symbol": "I6",
      "name": "First inversion (3rd in bass)",
      "chordNameInC": "C/E",
      "tones": "3rd in bass",
      "tier": "Simple"
    },
    {
      "symbol": "I64",
      "name": "Second inversion (5th in bass)",
      "chordNameInC": "C/G",
      "tones": "5th in bass",
      "tier": "Simple"
    },
    {
      "symbol": "V7",
      "name": "Dominant seventh",
      "chordNameInC": "G7",
      "tones": "1 3 5 b7",
      "tier": "Simple"
    },
    {
      "symbol": "vii°",
      "name": "Diminished triad",
      "chordNameInC": "B°",
      "tones": "1 b3 b5",
      "tier": "Simple"
    },
    {
      "symbol": "I+",
      "name": "Augmented triad",
      "chordNameInC": "C+",
      "tones": "1 3 #5",
      "tier": "Advanced"
    },
    {
      "symbol": "Imaj7",
      "name": "Major seventh",
      "chordNameInC": "Cmaj7",
      "tones": "1 3 5 7",
      "tier": "Simple"
    },
    {
      "symbol": "i7 / ii7",
      "name": "Minor seventh",
      "chordNameInC": "Cm7 / Dm7",
      "tones": "1 b3 5 b7",
      "tier": "Simple"
    },
    {
      "symbol": "vii°7",
      "name": "Diminished seventh",
      "chordNameInC": "B°7",
      "tones": "1 b3 b5 bb7",
      "tier": "Advanced"
    },
    {
      "symbol": "viiø7",
      "name": "Half-diminished seventh",
      "chordNameInC": "Bø7 (Bm7b5)",
      "tones": "1 b3 b5 b7",
      "tier": "Advanced"
    },
    {
      "symbol": "V65 / V43 / V42",
      "name": "Seventh-chord inversions (figured bass)",
      "chordNameInC": "G7/B · G7/D · G7/F",
      "tones": "3rd / 5th / 7th in bass",
      "tier": "Advanced"
    },
    {
      "symbol": "Isus4",
      "name": "Suspended fourth",
      "chordNameInC": "Csus4",
      "tones": "1 4 5",
      "tier": "Simple"
    },
    {
      "symbol": "Isus2",
      "name": "Suspended second",
      "chordNameInC": "Csus2",
      "tones": "1 2 5",
      "tier": "Simple"
    },
    {
      "symbol": "I(add9)",
      "name": "Added ninth",
      "chordNameInC": "Cadd9",
      "tones": "1 3 5 9",
      "tier": "Advanced"
    },
    {
      "symbol": "I5",
      "name": "Power chord (no 3rd)",
      "chordNameInC": "C5",
      "tones": "1 5",
      "tier": "Simple"
    },
    {
      "symbol": "V/V",
      "name": "Secondary dominant",
      "chordNameInC": "D7 (in C)",
      "tones": "dominant of the dominant",
      "tier": "Advanced"
    }
  ],
  "genres": [
    {
      "name": "Pop classic radio",
      "sections": [
        {
          "section": "Intro",
          "bars": [
            1,
            8
          ],
          "chords": [
            "I",
            "V",
            "vi",
            "IV",
            "I",
            "V",
            "vi",
            "IV"
          ]
        },
        {
          "section": "Verse 1",
          "bars": [
            9,
            24
          ],
          "chords": [
            "I",
            "V",
            "vi",
            "IV",
            "I",
            "V",
            "vi",
            "IV",
            "I",
            "V",
            "vi",
            "IV",
            "I",
            "V",
            "vi",
            "IV"
          ]
        },
        {
          "section": "Pre-chorus",
          "bars": [
            25,
            32
          ],
          "chords": [
            "IV",
            "V",
            "vi",
            "V",
            "IV",
            "V",
            "vi",
            "V"
          ]
        },
        {
          "section": "Chorus",
          "bars": [
            33,
            40
          ],
          "chords": [
            "I",
            "V",
            "vi",
            "IV",
            "I",
            "V",
            "vi",
            "IV"
          ]
        },
        {
          "section": "Verse 2",
          "bars": [
            41,
            56
          ],
          "chords": [
            "I",
            "V",
            "vi",
            "IV",
            "I",
            "V",
            "vi",
            "IV",
            "I",
            "V",
            "vi",
            "IV",
            "I",
            "V",
            "vi",
            "IV"
          ]
        },
        {
          "section": "Pre-chorus",
          "bars": [
            57,
            64
          ],
          "chords": [
            "IV",
            "V",
            "vi",
            "V",
            "IV",
            "V",
            "vi",
            "V"
          ]
        },
        {
          "section": "Chorus",
          "bars": [
            65,
            72
          ],
          "chords": [
            "I",
            "V",
            "vi",
            "IV",
            "I",
            "V",
            "vi",
            "IV"
          ]
        },
        {
          "section": "Bridge",
          "bars": [
            73,
            80
          ],
          "chords": [
            "vi",
            "IV",
            "I",
            "V",
            "vi",
            "IV",
            "I",
            "V"
          ]
        },
        {
          "section": "Chorus",
          "bars": [
            81,
            96
          ],
          "chords": [
            "I",
            "V",
            "vi",
            "IV",
            "I",
            "V",
            "vi",
            "IV",
            "I",
            "V",
            "vi",
            "IV",
            "I",
            "V",
            "vi",
            "IV"
          ]
        },
        {
          "section": "Outro",
          "bars": [
            97,
            104
          ],
          "chords": [
            "I",
            "V",
            "vi",
            "IV",
            "I",
            "V",
            "vi",
            "IV"
          ]
        }
      ]
    },
    {
      "name": "Pop shorter modern",
      "sections": [
        {
          "section": "Intro",
          "bars": [
            1,
            4
          ],
          "chords": [
            "I",
            "V",
            "vi",
            "IV"
          ]
        },
        {
          "section": "Verse 1",
          "bars": [
            5,
            12
          ],
          "chords": [
            "I",
            "V",
            "vi",
            "IV",
            "I",
            "V",
            "vi",
            "IV"
          ]
        },
        {
          "section": "Pre-chorus",
          "bars": [
            13,
            20
          ],
          "chords": [
            "IV",
            "V",
            "vi",
            "V",
            "IV",
            "V",
            "vi",
            "V"
          ]
        },
        {
          "section": "Chorus",
          "bars": [
            21,
            28
          ],
          "chords": [
            "I",
            "V",
            "vi",
            "IV",
            "I",
            "V",
            "vi",
            "IV"
          ]
        },
        {
          "section": "Verse 2",
          "bars": [
            29,
            36
          ],
          "chords": [
            "I",
            "V",
            "vi",
            "IV",
            "I",
            "V",
            "vi",
            "IV"
          ]
        },
        {
          "section": "Pre-chorus",
          "bars": [
            37,
            44
          ],
          "chords": [
            "IV",
            "V",
            "vi",
            "V",
            "IV",
            "V",
            "vi",
            "V"
          ]
        },
        {
          "section": "Chorus",
          "bars": [
            45,
            52
          ],
          "chords": [
            "I",
            "V",
            "vi",
            "IV",
            "I",
            "V",
            "vi",
            "IV"
          ]
        },
        {
          "section": "Bridge",
          "bars": [
            53,
            60
          ],
          "chords": [
            "vi",
            "IV",
            "I",
            "V",
            "vi",
            "IV",
            "I",
            "V"
          ]
        },
        {
          "section": "Chorus",
          "bars": [
            61,
            76
          ],
          "chords": [
            "I",
            "V",
            "vi",
            "IV",
            "I",
            "V",
            "vi",
            "IV",
            "I",
            "V",
            "vi",
            "IV",
            "I",
            "V",
            "vi",
            "IV"
          ]
        },
        {
          "section": "Outro",
          "bars": [
            77,
            80
          ],
          "chords": [
            "I",
            "V",
            "vi",
            "IV"
          ]
        }
      ]
    },
    {
      "name": "Pop no pre-chorus",
      "sections": [
        {
          "section": "Intro",
          "bars": [
            1,
            8
          ],
          "chords": [
            "IV",
            "I",
            "vi",
            "V",
            "IV",
            "I",
            "vi",
            "V"
          ]
        },
        {
          "section": "Verse 1",
          "bars": [
            9,
            24
          ],
          "chords": [
            "IV",
            "I",
            "vi",
            "V",
            "IV",
            "I",
            "vi",
            "V",
            "IV",
            "I",
            "vi",
            "V",
            "IV",
            "I",
            "vi",
            "V"
          ]
        },
        {
          "section": "Chorus",
          "bars": [
            25,
            32
          ],
          "chords": [
            "IV",
            "I",
            "vi",
            "V",
            "IV",
            "I",
            "vi",
            "V"
          ]
        },
        {
          "section": "Verse 2",
          "bars": [
            33,
            48
          ],
          "chords": [
            "IV",
            "I",
            "vi",
            "V",
            "IV",
            "I",
            "vi",
            "V",
            "IV",
            "I",
            "vi",
            "V",
            "IV",
            "I",
            "vi",
            "V"
          ]
        },
        {
          "section": "Chorus",
          "bars": [
            49,
            56
          ],
          "chords": [
            "IV",
            "I",
            "vi",
            "V",
            "IV",
            "I",
            "vi",
            "V"
          ]
        },
        {
          "section": "Bridge",
          "bars": [
            57,
            64
          ],
          "chords": [
            "vi",
            "IV",
            "I",
            "V",
            "vi",
            "IV",
            "I",
            "V"
          ]
        },
        {
          "section": "Chorus",
          "bars": [
            65,
            80
          ],
          "chords": [
            "IV",
            "I",
            "vi",
            "V",
            "IV",
            "I",
            "vi",
            "V",
            "IV",
            "I",
            "vi",
            "V",
            "IV",
            "I",
            "vi",
            "V"
          ]
        },
        {
          "section": "Outro",
          "bars": [
            81,
            88
          ],
          "chords": [
            "IV",
            "I",
            "vi",
            "V",
            "IV",
            "I",
            "vi",
            "V"
          ]
        }
      ]
    },
    {
      "name": "Pop chorus early",
      "sections": [
        {
          "section": "Intro",
          "bars": [
            1,
            4
          ],
          "chords": [
            "I",
            "V",
            "vi",
            "IV"
          ]
        },
        {
          "section": "Chorus",
          "bars": [
            5,
            12
          ],
          "chords": [
            "I",
            "V",
            "vi",
            "IV",
            "I",
            "V",
            "vi",
            "IV"
          ]
        },
        {
          "section": "Verse 1",
          "bars": [
            13,
            20
          ],
          "chords": [
            "I",
            "V",
            "vi",
            "IV",
            "I",
            "V",
            "vi",
            "IV"
          ]
        },
        {
          "section": "Pre-chorus",
          "bars": [
            21,
            24
          ],
          "chords": [
            "IV",
            "V",
            "vi",
            "V"
          ]
        },
        {
          "section": "Chorus",
          "bars": [
            25,
            32
          ],
          "chords": [
            "I",
            "V",
            "vi",
            "IV",
            "I",
            "V",
            "vi",
            "IV"
          ]
        },
        {
          "section": "Verse 2",
          "bars": [
            33,
            40
          ],
          "chords": [
            "I",
            "V",
            "vi",
            "IV",
            "I",
            "V",
            "vi",
            "IV"
          ]
        },
        {
          "section": "Pre-chorus",
          "bars": [
            41,
            44
          ],
          "chords": [
            "IV",
            "V",
            "vi",
            "V"
          ]
        },
        {
          "section": "Chorus",
          "bars": [
            45,
            52
          ],
          "chords": [
            "I",
            "V",
            "vi",
            "IV",
            "I",
            "V",
            "vi",
            "IV"
          ]
        },
        {
          "section": "Bridge",
          "bars": [
            53,
            60
          ],
          "chords": [
            "vi",
            "IV",
            "I",
            "V",
            "vi",
            "IV",
            "I",
            "V"
          ]
        },
        {
          "section": "Chorus",
          "bars": [
            61,
            76
          ],
          "chords": [
            "I",
            "V",
            "vi",
            "IV",
            "I",
            "V",
            "vi",
            "IV",
            "I",
            "V",
            "vi",
            "IV",
            "I",
            "V",
            "vi",
            "IV"
          ]
        },
        {
          "section": "Outro",
          "bars": [
            77,
            80
          ],
          "chords": [
            "I",
            "V",
            "vi",
            "IV"
          ]
        }
      ]
    },
    {
      "name": "Pop with post-chorus",
      "sections": [
        {
          "section": "Intro",
          "bars": [
            1,
            8
          ],
          "chords": [
            "I",
            "V",
            "vi",
            "IV",
            "I",
            "V",
            "vi",
            "IV"
          ]
        },
        {
          "section": "Verse 1",
          "bars": [
            9,
            24
          ],
          "chords": [
            "I",
            "V",
            "vi",
            "IV",
            "I",
            "V",
            "vi",
            "IV",
            "I",
            "V",
            "vi",
            "IV",
            "I",
            "V",
            "vi",
            "IV"
          ]
        },
        {
          "section": "Pre-chorus",
          "bars": [
            25,
            32
          ],
          "chords": [
            "IV",
            "V",
            "vi",
            "V",
            "IV",
            "V",
            "vi",
            "V"
          ]
        },
        {
          "section": "Chorus",
          "bars": [
            33,
            40
          ],
          "chords": [
            "I",
            "V",
            "vi",
            "IV",
            "I",
            "V",
            "vi",
            "IV"
          ]
        },
        {
          "section": "Post-chorus",
          "bars": [
            41,
            48
          ],
          "chords": [
            "I",
            "I",
            "IV",
            "IV",
            "I",
            "I",
            "V",
            "V"
          ]
        }
      ]
    },
    {
      "name": "Hip-hop",
      "sections": [
        {
          "section": "Intro",
          "bars": [
            1,
            8
          ],
          "chords": [
            "i",
            "VI",
            "VII",
            "i",
            "i",
            "VI",
            "VII",
            "i"
          ]
        },
        {
          "section": "Verse 1",
          "bars": [
            9,
            24
          ],
          "chords": [
            "i",
            "VI",
            "VII",
            "i",
            "i",
            "VI",
            "VII",
            "i",
            "i",
            "VI",
            "VII",
            "i",
            "i",
            "VI",
            "VII",
            "i"
          ]
        },
        {
          "section": "Hook",
          "bars": [
            25,
            32
          ],
          "chords": [
            "i",
            "VI",
            "VII",
            "i",
            "i",
            "VI",
            "VII",
            "i"
          ]
        },
        {
          "section": "Verse 2",
          "bars": [
            33,
            48
          ],
          "chords": [
            "i",
            "VI",
            "VII",
            "i",
            "i",
            "VI",
            "VII",
            "i",
            "i",
            "VI",
            "VII",
            "i",
            "i",
            "VI",
            "VII",
            "i"
          ]
        },
        {
          "section": "Hook",
          "bars": [
            49,
            56
          ],
          "chords": [
            "i",
            "VI",
            "VII",
            "i",
            "i",
            "VI",
            "VII",
            "i"
          ]
        },
        {
          "section": "Verse 3",
          "bars": [
            57,
            72
          ],
          "chords": [
            "i",
            "VI",
            "VII",
            "i",
            "i",
            "VI",
            "VII",
            "i",
            "i",
            "VI",
            "VII",
            "i",
            "i",
            "VI",
            "VII",
            "i"
          ]
        },
        {
          "section": "Hook",
          "bars": [
            73,
            80
          ],
          "chords": [
            "i",
            "VI",
            "VII",
            "i",
            "i",
            "VI",
            "VII",
            "i"
          ]
        },
        {
          "section": "Outro",
          "bars": [
            81,
            88
          ],
          "chords": [
            "i",
            "VI",
            "VII",
            "i",
            "i",
            "VI",
            "VII",
            "i"
          ]
        }
      ]
    },
    {
      "name": "Trap",
      "sections": [
        {
          "section": "Intro",
          "bars": [
            1,
            8
          ],
          "chords": [
            "i",
            "i",
            "i",
            "i",
            "VI",
            "VI",
            "VII",
            "i"
          ]
        },
        {
          "section": "Verse",
          "bars": [
            9,
            16
          ],
          "chords": [
            "i",
            "i",
            "i",
            "i",
            "VI",
            "VI",
            "VII",
            "i"
          ]
        },
        {
          "section": "Hook",
          "bars": [
            17,
            24
          ],
          "chords": [
            "i",
            "VI",
            "VII",
            "i",
            "i",
            "VI",
            "VII",
            "i"
          ]
        },
        {
          "section": "Verse",
          "bars": [
            25,
            32
          ],
          "chords": [
            "i",
            "i",
            "i",
            "i",
            "VI",
            "VI",
            "VII",
            "i"
          ]
        },
        {
          "section": "Hook",
          "bars": [
            33,
            40
          ],
          "chords": [
            "i",
            "VI",
            "VII",
            "i",
            "i",
            "VI",
            "VII",
            "i"
          ]
        },
        {
          "section": "Break",
          "bars": [
            41,
            44
          ],
          "chords": [
            "i",
            "i",
            "i",
            "VII"
          ]
        },
        {
          "section": "Hook",
          "bars": [
            45,
            52
          ],
          "chords": [
            "i",
            "VI",
            "VII",
            "i",
            "i",
            "VI",
            "VII",
            "i"
          ]
        },
        {
          "section": "Outro",
          "bars": [
            53,
            56
          ],
          "chords": [
            "i",
            "VI",
            "VII",
            "i"
          ]
        }
      ]
    },
    {
      "name": "R&B",
      "sections": [
        {
          "section": "Intro",
          "bars": [
            1,
            8
          ],
          "chords": [
            "Imaj7",
            "Imaj7",
            "IVmaj7",
            "IVmaj7",
            "Imaj7",
            "Imaj7",
            "IVmaj7",
            "IVmaj7"
          ]
        },
        {
          "section": "Verse 1",
          "bars": [
            9,
            16
          ],
          "chords": [
            "Imaj7",
            "Imaj7",
            "IVmaj7",
            "IVmaj7",
            "Imaj7",
            "Imaj7",
            "IVmaj7",
            "IVmaj7"
          ]
        },
        {
          "section": "Pre-chorus",
          "bars": [
            17,
            24
          ],
          "chords": [
            "ii7",
            "ii7",
            "ii7",
            "ii7",
            "V7",
            "V7",
            "V7",
            "V7"
          ]
        },
        {
          "section": "Chorus",
          "bars": [
            25,
            32
          ],
          "chords": [
            "Imaj7",
            "Imaj7",
            "vi7",
            "vi7",
            "IVmaj7",
            "IVmaj7",
            "V7",
            "V7"
          ]
        },
        {
          "section": "Verse 2",
          "bars": [
            33,
            40
          ],
          "chords": [
            "Imaj7",
            "Imaj7",
            "IVmaj7",
            "IVmaj7",
            "Imaj7",
            "Imaj7",
            "IVmaj7",
            "IVmaj7"
          ]
        },
        {
          "section": "Pre-chorus",
          "bars": [
            41,
            48
          ],
          "chords": [
            "ii7",
            "ii7",
            "ii7",
            "ii7",
            "V7",
            "V7",
            "V7",
            "V7"
          ]
        },
        {
          "section": "Chorus",
          "bars": [
            49,
            56
          ],
          "chords": [
            "Imaj7",
            "Imaj7",
            "vi7",
            "vi7",
            "IVmaj7",
            "IVmaj7",
            "V7",
            "V7"
          ]
        },
        {
          "section": "Bridge",
          "bars": [
            57,
            64
          ],
          "chords": [
            "vi7",
            "vi7",
            "IVmaj7",
            "IVmaj7",
            "ii7",
            "ii7",
            "V7",
            "V7"
          ]
        },
        {
          "section": "Chorus",
          "bars": [
            65,
            80
          ],
          "chords": [
            "Imaj7",
            "Imaj7",
            "vi7",
            "vi7",
            "IVmaj7",
            "IVmaj7",
            "V7",
            "V7",
            "Imaj7",
            "Imaj7",
            "vi7",
            "vi7",
            "IVmaj7",
            "IVmaj7",
            "V7",
            "V7"
          ]
        },
        {
          "section": "Outro",
          "bars": [
            81,
            88
          ],
          "chords": [
            "Imaj7",
            "Imaj7",
            "IVmaj7",
            "IVmaj7",
            "Imaj7",
            "Imaj7",
            "V7",
            "Imaj7"
          ]
        }
      ]
    },
    {
      "name": "Funk",
      "sections": [
        {
          "section": "Intro vamp",
          "bars": [
            1,
            4
          ],
          "chords": [
            "I7",
            "I7",
            "IV7",
            "I7"
          ]
        },
        {
          "section": "Verse",
          "bars": [
            5,
            12
          ],
          "chords": [
            "I7",
            "I7",
            "IV7",
            "I7",
            "I7",
            "I7",
            "IV7",
            "I7"
          ]
        },
        {
          "section": "Hook",
          "bars": [
            13,
            20
          ],
          "chords": [
            "I7",
            "I7",
            "IV7",
            "I7",
            "I7",
            "I7",
            "IV7",
            "V7"
          ]
        },
        {
          "section": "Verse",
          "bars": [
            21,
            28
          ],
          "chords": [
            "I7",
            "I7",
            "IV7",
            "I7",
            "I7",
            "I7",
            "IV7",
            "I7"
          ]
        },
        {
          "section": "Hook",
          "bars": [
            29,
            36
          ],
          "chords": [
            "I7",
            "I7",
            "IV7",
            "I7",
            "I7",
            "I7",
            "IV7",
            "V7"
          ]
        },
        {
          "section": "Breakdown",
          "bars": [
            37,
            44
          ],
          "chords": [
            "I7",
            "I7",
            "I7",
            "I7",
            "IV7",
            "IV7",
            "V7",
            "I7"
          ]
        },
        {
          "section": "Hook",
          "bars": [
            45,
            52
          ],
          "chords": [
            "I7",
            "I7",
            "IV7",
            "I7",
            "I7",
            "I7",
            "IV7",
            "V7"
          ]
        },
        {
          "section": "Outro vamp",
          "bars": [
            53,
            56
          ],
          "chords": [
            "I7",
            "IV7",
            "V7",
            "I7"
          ]
        }
      ]
    },
    {
      "name": "Disco",
      "sections": [
        {
          "section": "Intro",
          "bars": [
            1,
            8
          ],
          "chords": [
            "I",
            "V",
            "vi",
            "IV",
            "I",
            "V",
            "vi",
            "IV"
          ]
        },
        {
          "section": "Verse 1",
          "bars": [
            9,
            16
          ],
          "chords": [
            "I",
            "V",
            "vi",
            "IV",
            "I",
            "V",
            "vi",
            "IV"
          ]
        },
        {
          "section": "Chorus",
          "bars": [
            17,
            24
          ],
          "chords": [
            "I",
            "V",
            "vi",
            "IV",
            "I",
            "V",
            "vi",
            "IV"
          ]
        },
        {
          "section": "Verse 2",
          "bars": [
            25,
            32
          ],
          "chords": [
            "I",
            "V",
            "vi",
            "IV",
            "I",
            "V",
            "vi",
            "IV"
          ]
        },
        {
          "section": "Chorus",
          "bars": [
            33,
            40
          ],
          "chords": [
            "I",
            "V",
            "vi",
            "IV",
            "I",
            "V",
            "vi",
            "IV"
          ]
        },
        {
          "section": "Break",
          "bars": [
            41,
            48
          ],
          "chords": [
            "IV",
            "IV",
            "V",
            "V",
            "vi",
            "vi",
            "V",
            "V"
          ]
        },
        {
          "section": "Chorus",
          "bars": [
            49,
            64
          ],
          "chords": [
            "I",
            "V",
            "vi",
            "IV",
            "I",
            "V",
            "vi",
            "IV",
            "I",
            "V",
            "vi",
            "IV",
            "I",
            "V",
            "vi",
            "IV"
          ]
        },
        {
          "section": "Outro",
          "bars": [
            65,
            72
          ],
          "chords": [
            "I",
            "V",
            "vi",
            "IV",
            "I",
            "V",
            "vi",
            "I"
          ]
        }
      ]
    },
    {
      "name": "EDM",
      "sections": [
        {
          "section": "Intro",
          "bars": [
            1,
            16
          ],
          "chords": [
            "i",
            "VI",
            "III",
            "VII",
            "i",
            "VI",
            "III",
            "VII",
            "i",
            "VI",
            "III",
            "VII",
            "i",
            "VI",
            "III",
            "VII"
          ]
        },
        {
          "section": "Build",
          "bars": [
            17,
            32
          ],
          "chords": [
            "i",
            "VI",
            "III",
            "VII",
            "i",
            "VI",
            "III",
            "VII",
            "i",
            "VI",
            "III",
            "VII",
            "V",
            "V",
            "V",
            "V"
          ]
        },
        {
          "section": "Drop",
          "bars": [
            33,
            48
          ],
          "chords": [
            "i",
            "VI",
            "III",
            "VII",
            "i",
            "VI",
            "III",
            "VII",
            "i",
            "VI",
            "III",
            "VII",
            "i",
            "VI",
            "III",
            "VII"
          ]
        },
        {
          "section": "Breakdown",
          "bars": [
            49,
            64
          ],
          "chords": [
            "vi",
            "vi",
            "vi",
            "vi",
            "IV",
            "IV",
            "IV",
            "IV",
            "vi",
            "vi",
            "vi",
            "vi",
            "V",
            "V",
            "V",
            "V"
          ]
        },
        {
          "section": "Build",
          "bars": [
            65,
            80
          ],
          "chords": [
            "i",
            "VI",
            "III",
            "VII",
            "i",
            "VI",
            "III",
            "VII",
            "i",
            "VI",
            "III",
            "VII",
            "V",
            "V",
            "V",
            "V"
          ]
        },
        {
          "section": "Drop",
          "bars": [
            81,
            96
          ],
          "chords": [
            "i",
            "VI",
            "III",
            "VII",
            "i",
            "VI",
            "III",
            "VII",
            "i",
            "VI",
            "III",
            "VII",
            "i",
            "VI",
            "III",
            "VII"
          ]
        },
        {
          "section": "Outro",
          "bars": [
            97,
            112
          ],
          "chords": [
            "i",
            "VI",
            "III",
            "VII",
            "i",
            "VI",
            "III",
            "VII",
            "i",
            "i",
            "i",
            "i",
            "i",
            "i",
            "i",
            "i"
          ]
        }
      ]
    },
    {
      "name": "Country",
      "sections": [
        {
          "section": "Intro",
          "bars": [
            1,
            8
          ],
          "chords": [
            "I",
            "I",
            "IV",
            "IV",
            "V",
            "V",
            "I",
            "I"
          ]
        },
        {
          "section": "Verse 1",
          "bars": [
            9,
            16
          ],
          "chords": [
            "I",
            "I",
            "I",
            "I",
            "IV",
            "IV",
            "V",
            "I"
          ]
        },
        {
          "section": "Chorus",
          "bars": [
            17,
            24
          ],
          "chords": [
            "I",
            "I",
            "IV",
            "IV",
            "V",
            "V",
            "I",
            "I"
          ]
        },
        {
          "section": "Verse 2",
          "bars": [
            25,
            32
          ],
          "chords": [
            "I",
            "I",
            "I",
            "I",
            "IV",
            "IV",
            "V",
            "I"
          ]
        },
        {
          "section": "Chorus",
          "bars": [
            33,
            40
          ],
          "chords": [
            "I",
            "I",
            "IV",
            "IV",
            "V",
            "V",
            "I",
            "I"
          ]
        },
        {
          "section": "Bridge",
          "bars": [
            41,
            48
          ],
          "chords": [
            "IV",
            "IV",
            "I",
            "I",
            "V",
            "V",
            "I",
            "I"
          ]
        },
        {
          "section": "Chorus",
          "bars": [
            49,
            64
          ],
          "chords": [
            "I",
            "I",
            "IV",
            "IV",
            "V",
            "V",
            "I",
            "I",
            "I",
            "I",
            "IV",
            "IV",
            "V",
            "V",
            "I",
            "I"
          ]
        },
        {
          "section": "Outro",
          "bars": [
            65,
            72
          ],
          "chords": [
            "I",
            "I",
            "IV",
            "IV",
            "V",
            "V",
            "I",
            "I"
          ]
        }
      ]
    },
    {
      "name": "Folk",
      "sections": [
        {
          "section": "Intro",
          "bars": [
            1,
            4
          ],
          "chords": [
            "I",
            "V",
            "vi",
            "IV"
          ]
        },
        {
          "section": "Verse 1",
          "bars": [
            5,
            12
          ],
          "chords": [
            "I",
            "V",
            "vi",
            "IV",
            "I",
            "V",
            "vi",
            "IV"
          ]
        },
        {
          "section": "Refrain",
          "bars": [
            13,
            16
          ],
          "chords": [
            "I",
            "IV",
            "V",
            "I"
          ]
        },
        {
          "section": "Verse 2",
          "bars": [
            17,
            24
          ],
          "chords": [
            "I",
            "V",
            "vi",
            "IV",
            "I",
            "V",
            "vi",
            "IV"
          ]
        },
        {
          "section": "Refrain",
          "bars": [
            25,
            28
          ],
          "chords": [
            "I",
            "IV",
            "V",
            "I"
          ]
        },
        {
          "section": "Verse 3",
          "bars": [
            29,
            36
          ],
          "chords": [
            "I",
            "V",
            "vi",
            "IV",
            "I",
            "V",
            "vi",
            "IV"
          ]
        },
        {
          "section": "Refrain",
          "bars": [
            37,
            40
          ],
          "chords": [
            "I",
            "IV",
            "V",
            "I"
          ]
        },
        {
          "section": "Outro",
          "bars": [
            41,
            44
          ],
          "chords": [
            "I",
            "IV",
            "V",
            "I"
          ]
        }
      ]
    },
    {
      "name": "Blues 12-bar",
      "sections": [
        {
          "section": "Chorus",
          "bars": [
            1,
            12
          ],
          "chords": [
            "I7",
            "I7",
            "I7",
            "I7",
            "IV7",
            "IV7",
            "I7",
            "I7",
            "V7",
            "IV7",
            "I7",
            "V7"
          ]
        }
      ]
    },
    {
      "name": "Blues 8-bar",
      "sections": [
        {
          "section": "Chorus",
          "bars": [
            1,
            8
          ],
          "chords": [
            "I7",
            "I7",
            "IV7",
            "IV7",
            "I7",
            "V7",
            "I7",
            "V7"
          ]
        }
      ]
    },
    {
      "name": "Jazz AABA",
      "sections": [
        {
          "section": "A",
          "bars": [
            1,
            8
          ],
          "chords": [
            "ii7",
            "ii7",
            "V7",
            "V7",
            "Imaj7",
            "Imaj7",
            "vi7",
            "V7"
          ]
        },
        {
          "section": "A",
          "bars": [
            9,
            16
          ],
          "chords": [
            "ii7",
            "ii7",
            "V7",
            "V7",
            "Imaj7",
            "Imaj7",
            "vi7",
            "V7"
          ]
        },
        {
          "section": "B",
          "bars": [
            17,
            24
          ],
          "chords": [
            "IV",
            "IV",
            "II7",
            "II7",
            "ii7",
            "ii7",
            "V7",
            "V7"
          ]
        },
        {
          "section": "A",
          "bars": [
            25,
            32
          ],
          "chords": [
            "ii7",
            "ii7",
            "V7",
            "V7",
            "I",
            "vi",
            "ii",
            "V"
          ]
        }
      ]
    },
    {
      "name": "Reggae",
      "sections": [
        {
          "section": "Intro",
          "bars": [
            1,
            8
          ],
          "chords": [
            "I",
            "V",
            "vi",
            "IV",
            "I",
            "V",
            "vi",
            "IV"
          ]
        },
        {
          "section": "Verse 1",
          "bars": [
            9,
            16
          ],
          "chords": [
            "I",
            "V",
            "vi",
            "IV",
            "I",
            "V",
            "vi",
            "IV"
          ]
        },
        {
          "section": "Hook",
          "bars": [
            17,
            24
          ],
          "chords": [
            "I",
            "V",
            "vi",
            "IV",
            "I",
            "V",
            "vi",
            "IV"
          ]
        },
        {
          "section": "Verse 2",
          "bars": [
            25,
            32
          ],
          "chords": [
            "I",
            "V",
            "vi",
            "IV",
            "I",
            "V",
            "vi",
            "IV"
          ]
        },
        {
          "section": "Hook",
          "bars": [
            33,
            40
          ],
          "chords": [
            "I",
            "V",
            "vi",
            "IV",
            "I",
            "V",
            "vi",
            "IV"
          ]
        },
        {
          "section": "Bridge",
          "bars": [
            41,
            48
          ],
          "chords": [
            "vi",
            "IV",
            "I",
            "V",
            "vi",
            "IV",
            "I",
            "V"
          ]
        },
        {
          "section": "Hook",
          "bars": [
            49,
            56
          ],
          "chords": [
            "I",
            "V",
            "vi",
            "IV",
            "I",
            "V",
            "vi",
            "IV"
          ]
        },
        {
          "section": "Outro",
          "bars": [
            57,
            64
          ],
          "chords": [
            "I",
            "V",
            "vi",
            "IV",
            "I",
            "V",
            "vi",
            "I"
          ]
        }
      ]
    },
    {
      "name": "Latin",
      "sections": [
        {
          "section": "Intro",
          "bars": [
            1,
            8
          ],
          "chords": [
            "I",
            "IV",
            "V",
            "I",
            "I",
            "IV",
            "V",
            "I"
          ]
        },
        {
          "section": "Verse",
          "bars": [
            9,
            16
          ],
          "chords": [
            "I",
            "IV",
            "V",
            "I",
            "I",
            "IV",
            "V",
            "I"
          ]
        },
        {
          "section": "Coro",
          "bars": [
            17,
            24
          ],
          "chords": [
            "I",
            "IV",
            "V",
            "I",
            "I",
            "IV",
            "V",
            "I"
          ]
        },
        {
          "section": "Verse",
          "bars": [
            25,
            32
          ],
          "chords": [
            "I",
            "IV",
            "V",
            "I",
            "I",
            "IV",
            "V",
            "I"
          ]
        },
        {
          "section": "Coro",
          "bars": [
            33,
            40
          ],
          "chords": [
            "I",
            "IV",
            "V",
            "I",
            "I",
            "IV",
            "V",
            "I"
          ]
        },
        {
          "section": "Montuno",
          "bars": [
            41,
            56
          ],
          "chords": [
            "I",
            "IV",
            "V",
            "I",
            "I",
            "IV",
            "V",
            "I",
            "I",
            "IV",
            "V",
            "I",
            "I",
            "IV",
            "V",
            "I"
          ]
        },
        {
          "section": "Coro",
          "bars": [
            57,
            64
          ],
          "chords": [
            "I",
            "IV",
            "V",
            "I",
            "I",
            "IV",
            "V",
            "I"
          ]
        },
        {
          "section": "Outro",
          "bars": [
            65,
            72
          ],
          "chords": [
            "I",
            "IV",
            "V",
            "I",
            "I",
            "IV",
            "V",
            "I"
          ]
        }
      ]
    },
    {
      "name": "Gospel",
      "sections": [
        {
          "section": "Intro",
          "bars": [
            1,
            8
          ],
          "chords": [
            "I",
            "I",
            "IV",
            "IV",
            "V",
            "V",
            "I",
            "I"
          ]
        },
        {
          "section": "Verse 1",
          "bars": [
            9,
            16
          ],
          "chords": [
            "I",
            "I",
            "IV",
            "IV",
            "V",
            "V",
            "I",
            "I"
          ]
        },
        {
          "section": "Chorus",
          "bars": [
            17,
            24
          ],
          "chords": [
            "I",
            "I",
            "IV",
            "IV",
            "V",
            "V",
            "I",
            "I"
          ]
        },
        {
          "section": "Verse 2",
          "bars": [
            25,
            32
          ],
          "chords": [
            "I",
            "I",
            "IV",
            "IV",
            "V",
            "V",
            "I",
            "I"
          ]
        },
        {
          "section": "Chorus",
          "bars": [
            33,
            40
          ],
          "chords": [
            "I",
            "I",
            "IV",
            "IV",
            "V",
            "V",
            "I",
            "I"
          ]
        },
        {
          "section": "Vamp",
          "bars": [
            41,
            56
          ],
          "chords": [
            "I",
            "IV",
            "V",
            "I",
            "I",
            "IV",
            "V",
            "I",
            "I",
            "IV",
            "V",
            "I",
            "I",
            "IV",
            "V",
            "I"
          ]
        },
        {
          "section": "Chorus",
          "bars": [
            57,
            64
          ],
          "chords": [
            "I",
            "I",
            "IV",
            "IV",
            "V",
            "V",
            "I",
            "I"
          ]
        },
        {
          "section": "Tag",
          "bars": [
            65,
            68
          ],
          "chords": [
            "V",
            "V",
            "V",
            "I"
          ]
        }
      ]
    },
    {
      "name": "Metal",
      "sections": [
        {
          "section": "Intro riff",
          "bars": [
            1,
            8
          ],
          "chords": [
            "i",
            "i",
            "bVII",
            "bVI",
            "bVII",
            "bVII",
            "i",
            "i"
          ]
        },
        {
          "section": "Verse 1",
          "bars": [
            9,
            16
          ],
          "chords": [
            "i",
            "bVII",
            "bVI",
            "bVII",
            "i",
            "bVII",
            "bVI",
            "bVII"
          ]
        },
        {
          "section": "Chorus",
          "bars": [
            17,
            24
          ],
          "chords": [
            "i",
            "i",
            "bVII",
            "bVII",
            "bVI",
            "bVI",
            "bVII",
            "i"
          ]
        },
        {
          "section": "Verse 2",
          "bars": [
            25,
            32
          ],
          "chords": [
            "i",
            "bVII",
            "bVI",
            "bVII",
            "i",
            "bVII",
            "bVI",
            "bVII"
          ]
        },
        {
          "section": "Chorus",
          "bars": [
            33,
            40
          ],
          "chords": [
            "i",
            "i",
            "bVII",
            "bVII",
            "bVI",
            "bVI",
            "bVII",
            "i"
          ]
        },
        {
          "section": "Bridge / solo",
          "bars": [
            41,
            48
          ],
          "chords": [
            "i",
            "i",
            "bVI",
            "bVI",
            "bVII",
            "bVII",
            "i",
            "i"
          ]
        },
        {
          "section": "Breakdown",
          "bars": [
            49,
            56
          ],
          "chords": [
            "i",
            "i",
            "i",
            "i",
            "bVI",
            "bVI",
            "bVII",
            "bVII"
          ]
        },
        {
          "section": "Chorus",
          "bars": [
            57,
            64
          ],
          "chords": [
            "i",
            "i",
            "bVII",
            "bVII",
            "bVI",
            "bVI",
            "bVII",
            "i"
          ]
        },
        {
          "section": "Outro riff",
          "bars": [
            65,
            72
          ],
          "chords": [
            "i",
            "i",
            "bVII",
            "bVI",
            "bVII",
            "bVII",
            "i",
            "i"
          ]
        }
      ]
    },
    {
      "name": "Classical period",
      "sections": [
        {
          "section": "Antecedent",
          "bars": [
            1,
            4
          ],
          "chords": [
            "I",
            "I",
            "V",
            "V"
          ]
        },
        {
          "section": "Consequent",
          "bars": [
            5,
            8
          ],
          "chords": [
            "I",
            "IV",
            "V",
            "I"
          ]
        }
      ]
    },
    {
      "name": "Classical sentence",
      "sections": [
        {
          "section": "Presentation",
          "bars": [
            1,
            4
          ],
          "chords": [
            "I",
            "I",
            "V",
            "V"
          ]
        },
        {
          "section": "Continuation",
          "bars": [
            5,
            8
          ],
          "chords": [
            "vi",
            "IV",
            "V",
            "I"
          ]
        }
      ]
    },
    {
      "name": "Classical Pachelbel",
      "sections": [
        {
          "section": "Period",
          "bars": [
            1,
            8
          ],
          "chords": [
            "I",
            "V",
            "vi",
            "iii",
            "IV",
            "I",
            "IV",
            "V"
          ]
        }
      ]
    },
    {
      "name": "Classical binary",
      "sections": [
        {
          "section": "A",
          "bars": [
            1,
            8
          ],
          "chords": [
            "I",
            "I",
            "V",
            "V",
            "I",
            "IV",
            "V",
            "I"
          ]
        },
        {
          "section": "B",
          "bars": [
            9,
            16
          ],
          "chords": [
            "V",
            "V",
            "I",
            "I",
            "IV",
            "V",
            "V",
            "I"
          ]
        }
      ]
    },
    {
      "name": "Classical ternary",
      "sections": [
        {
          "section": "A",
          "bars": [
            1,
            8
          ],
          "chords": [
            "I",
            "I",
            "V",
            "V",
            "I",
            "IV",
            "V",
            "I"
          ]
        },
        {
          "section": "B",
          "bars": [
            9,
            16
          ],
          "chords": [
            "vi",
            "vi",
            "IV",
            "IV",
            "V",
            "V",
            "I",
            "I"
          ]
        },
        {
          "section": "A",
          "bars": [
            17,
            24
          ],
          "chords": [
            "I",
            "I",
            "V",
            "V",
            "I",
            "IV",
            "V",
            "I"
          ]
        }
      ]
    }
  ],
  "genrePatternMap": [
    {
      "genre": "Pop classic radio",
      "defaultBpm": 116,
      "meter": "4/4"
    },
    {
      "genre": "Pop shorter modern",
      "defaultBpm": 112,
      "meter": "4/4"
    },
    {
      "genre": "Pop no pre-chorus",
      "defaultBpm": 108,
      "meter": "4/4"
    },
    {
      "genre": "Pop chorus early",
      "defaultBpm": 120,
      "meter": "4/4"
    },
    {
      "genre": "Pop with post-chorus",
      "defaultBpm": 114,
      "meter": "4/4"
    },
    {
      "genre": "Hip-hop",
      "defaultBpm": 90,
      "meter": "4/4"
    },
    {
      "genre": "Trap",
      "defaultBpm": 140,
      "meter": "4/4"
    },
    {
      "genre": "R&B",
      "defaultBpm": 78,
      "meter": "4/4"
    },
    {
      "genre": "Funk",
      "defaultBpm": 104,
      "meter": "4/4"
    },
    {
      "genre": "Disco",
      "defaultBpm": 118,
      "meter": "4/4"
    },
    {
      "genre": "EDM",
      "defaultBpm": 126,
      "meter": "4/4"
    },
    {
      "genre": "Country",
      "defaultBpm": 112,
      "meter": "4/4"
    },
    {
      "genre": "Folk",
      "defaultBpm": 92,
      "meter": "4/4"
    },
    {
      "genre": "Blues 12-bar",
      "defaultBpm": 92,
      "meter": "4/4"
    },
    {
      "genre": "Blues 8-bar",
      "defaultBpm": 68,
      "meter": "4/4"
    },
    {
      "genre": "Jazz AABA",
      "defaultBpm": 132,
      "meter": "4/4"
    },
    {
      "genre": "Reggae",
      "defaultBpm": 74,
      "meter": "4/4"
    },
    {
      "genre": "Latin",
      "defaultBpm": 102,
      "meter": "4/4"
    },
    {
      "genre": "Gospel",
      "defaultBpm": 80,
      "meter": "4/4"
    },
    {
      "genre": "Metal",
      "defaultBpm": 150,
      "meter": "4/4"
    },
    {
      "genre": "Classical period",
      "defaultBpm": 100,
      "meter": "4/4"
    },
    {
      "genre": "Classical sentence",
      "defaultBpm": 104,
      "meter": "4/4"
    },
    {
      "genre": "Classical Pachelbel",
      "defaultBpm": 70,
      "meter": "4/4"
    },
    {
      "genre": "Classical binary",
      "defaultBpm": 96,
      "meter": "4/4"
    },
    {
      "genre": "Classical ternary",
      "defaultBpm": 96,
      "meter": "4/4"
    }
  ]
};
